$(document).ready(function(){
	$(".about").click(function(){
		$(".wrapMain").animate({
			scrollTop:0
		},300)
	}),
	$(".education").click(function(){
		$(".wrapMain").animate({
			scrollTop:550},300)
	}),
	$(".skills").click(function(){
		$(".wrapMain").animate({
			scrollTop:1110},300)
	}),
	$(".exp").click(function(){
		$(".wrapMain").animate({
			scrollTop:1695
		},300)
	})
});